name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  issue:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
    - name: Create an issue
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # GitHub handle of the user(s) to assign the issue (comma-separated)
        assignees: shubham0108
        # Number of the milestone to assign the issue to
        milestone: test 
