on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

uses: fjogeleit/http-request-action@master
            with:
                url: 'https://prod-56.westus.logic.azure.com:443/workflows/3be0d0c1205d4b5aa5ca67d992916643/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AW8pY5d7dZaayU_E_ex2_ZMd05MgjQ-UpH6My0ebau0'
                method: 'POST'
