on: 
    push:
        
         name: Create Milestone
         uses: WyriHaximus/github-action-create-milestone@0.1.0
          with:
 
            title: Before Approval 
        name: Create an issue
   - uses: actions/checkout@v2
  - uses: JasonEtco/create-an-issue@v2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      assignees: shubham0108
      
    issues:
        types: [closed]
        name: Create Another Milestone
         uses: WyriHaximus/github-action-create-milestone@0.1.0
          with:
 
            title: Approval Completed
  
   
    

  
