on: [push]
name: Make a HTTP request
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Variable Demo
        id: step_one
        run : echo"::set-output name=this::hello"
      - name: Test it
        run: echo ${{ steps.step_one.outputs.this }}  
     
